### ISSUE TITLE
make mail input component functional (and restructure)

### ISSUE THREAD

**Issue by ivoriginal** [ToolsForCommunities/communitytools.co#4]
<img width="578" alt="Screenshot 2019-12-27 at 16 17 18" src="https://user-images.githubusercontent.com/10926362/71522299-60be3280-28c4-11ea-8722-d87095f590f5.png">

**Comment by CodingCarlos** [comment]
I've got it working with Hubspot. Is any other place we want to add the mails? (i.e. some email marketing tool) @ivoriginal 

Also, there's no "allow" checkbox, what about #8 ?

**Comment by ivoriginal** [comment]
I want to check GDPR to be 100% sure that we have to use the checkbox or explore other ways of asking for consent

**Comment by ivoriginal** [comment]
Also: no, there's no need to use more tools for the moment. Thanks MACHINE.
